# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-redirect-from

# Site settings
title: "Comepaolo"
description: >
  Code, thoughts, and tales from Jesi e dintorni.

email: riccardo.maldini@gmail.com

#blog logo
logo: "/assets/images/logo.jpg"
float_logo: true

# blog cover
cover: "/assets/images/background_image.jpg"

name: "Riccardo Maldini"
author: "Riccardo Maldini"
author_image: "/assets/images/author.jpg"
author_bio: "Born to make fumé, forced to scale legacy systems."

paginate: 5

url: "https://maldins46.github.io" # the base hostname & protocol for your site
baseurl: "/comepaolo-blog"
#used to display twitter cards
twitter_handle: "@comepaolo_official"

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon: github
    url: https://github.com/maldins46
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: envelope-o
    url: "mailto:riccardo.maldini@gmail.com"
    desc: Contact me via email
    share_url:
    share_title:
    share_link:

  - icon: linkedin
    url: https://www.linkedin.com/in/riccardo-maldini-a6b684132/
    desc: Find me on LinkedIn
    share_url: //www.linkedin.com/shareArticle?mini=true
    share_title: "&title="
    share_link: "&url="

  - icon: instagram
    url: https://www.instagram.com/maldini_comepaolo
    desc: Connect with me on Instagram
    share_url:
    share_title:
    share_link:

  - icon: id-card-o
    url: https://github.com/maldins46/MaldiniCV/releases/latest/download/cv-maldini.pdf
    desc: Download my CV
    share_url:
    share_title:
    share_link:

  - icon: cc-paypal
    url: https://www.paypal.me/riccardomaldini
    desc: Donate on PayPal
    share_url:
    share_title:
    share_link:
